## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
q=[[4,5,6],[7,4,8]]
w=[[2,11,9],[1,3,6]]
def mul (x,y):
    assert len(x)==len(y) #if 2 len of matrices not equal print assert error 
    return [x_i*y_i for x_i,y_i in zip(x,y)]
def multi_2_matrices(q,w):
    c=[]
    for i in range(len(q)):
        c.append(mul(q[i],w[i]))
    return c
print(multi_2_matrices(q,w))

[[8, 55, 54], [7, 12, 48]]


## Write a NumPy program to compute the determinant of a given square array

In [5]:
import numpy as np
arr= np.arange(0,11)
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#sqrt array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

## Write a NumPy program to compute the cross product of two given vectors

In [8]:
#two given vectors
a=[[1,2,3],[2,5,8]]
b=[[3,6,4],[1,5,7]]
#cross product of two given vectors
np.cross(a,b)

array([[-10,   5,   0],
       [ -5,  -6,   5]])

## Write a NumPy program to compute the condition number of a given matrix

In [4]:
#the condition number of a given matrix
from numpy import linalg as la
a=[[4,7],[3,6]]
print(la.cond(a))

36.63937362366127


## Write a NumPy program to compute the inverse of a given matrix